#!/bin/bash
#
# Fix IPsec config to match working demo configuration
# This uses the EXACT format that works in demo_vpn_config
#

echo "🔧 Fixing IPsec config to match working configuration..."

# Stop strongswan
systemctl stop strongswan

# Create IPsec config matching the working demo format EXACTLY
cat > /etc/ipsec.conf << 'EOF'
# AWS Site-to-Site VPN Configuration
# Generated by VPN Manager

config setup
    charondebug="ike 2, knl 2, cfg 2, net 2, esp 2, dmn 2, mgr 2"
    uniqueids=no

conn Tunnel1
    auto=start
    left=%defaultroute
    leftid=%any
    right=52.223.2.21
    type=tunnel
    ikelifetime=8h
    keylife=1h
    rekeymargin=3m
    keyingtries=%forever
    keyexchange=ikev1
    ike=aes128-sha1-modp1024
    esp=aes128-sha1-modp1024
    auth=psk
    dpdaction=restart
    dpddelay=10s
    dpdtimeout=30s
    leftupdown=/etc/ipsec.d/aws-updown.sh
    mark=1
    replay_window=128

conn Tunnel2
    auto=start
    left=%defaultroute
    leftid=%any
    right=166.117.219.107
    type=tunnel
    ikelifetime=8h
    keylife=1h
    rekeymargin=3m
    keyingtries=%forever
    keyexchange=ikev1
    ike=aes128-sha1-modp1024
    esp=aes128-sha1-modp1024
    auth=psk
    dpdaction=restart
    dpddelay=10s
    dpdtimeout=30s
    leftupdown=/etc/ipsec.d/aws-updown.sh
    mark=2
    replay_window=128
EOF

# Update IPsec secrets to match working format
cat > /etc/ipsec.secrets << 'EOF'
# IPsec Secrets - Generated by VPN Manager

%any 52.223.2.21 : PSK "g137ja61eIfe5Tbzv7dSf7qb0_JrM6Sj"
%any 166.117.219.107 : PSK "_VBiaBA2FCHmqlWS39e_5bOrHcNL0Utn"
EOF

chmod 600 /etc/ipsec.secrets

# Copy to /etc/vpn/
cp /etc/ipsec.conf /etc/vpn/ipsec.conf
cp /etc/ipsec.secrets /etc/vpn/ipsec.secrets

# Recreate VTI interfaces matching working format EXACTLY
echo "🔗 Recreating VTI interfaces..."

# Delete existing
ip link del vti1 2>/dev/null || true
ip link del vti2 2>/dev/null || true

# Create VTI interfaces - EXACT format from working config
ip tunnel add vti1 mode vti local 0.0.0.0 remote 52.223.2.21 key 1
ip addr add 169.254.55.54/30 dev vti1
ip link set vti1 up mtu 1419
sysctl -w net.ipv4.conf.vti1.disable_policy=1
sysctl -w net.ipv4.conf.vti1.rp_filter=2

ip tunnel add vti2 mode vti local 0.0.0.0 remote 166.117.219.107 key 2
ip addr add 169.254.253.50/30 dev vti2
ip link set vti2 up mtu 1419
sysctl -w net.ipv4.conf.vti2.disable_policy=1
sysctl -w net.ipv4.conf.vti2.rp_filter=2

echo "✅ VTI interfaces recreated"

# Start strongswan
systemctl start strongswan

# Wait for tunnels to establish
echo "⏳ Waiting for tunnels to establish..."
sleep 15

# Check IPsec status
echo ""
echo "📊 IPsec Status:"
ipsec status

echo ""
echo "📊 Detailed Status:"
ipsec statusall | grep -E "Tunnel|ESTABLISHED|INSTALLED|bytes"

# Test ping
echo ""
echo "🔍 Testing connectivity..."
echo "Ping AWS Tunnel 1 inside IP:"
ping -c 5 -W 2 169.254.55.53

echo ""
echo "Ping AWS Tunnel 2 inside IP:"
ping -c 5 -W 2 169.254.253.49

# Wait for BGP
echo ""
echo "⏳ Waiting for BGP to establish..."
sleep 15

# Check BGP
echo ""
echo "📊 BGP Status:"
vtysh -c "show bgp summary"

echo ""
echo "📊 BGP Neighbors Detail:"
vtysh -c "show bgp neighbors" | grep -E "BGP state|remote router ID|Connections established"

echo ""
echo "✅ Configuration updated to match working format!"
echo ""
echo "Key changes made:"
echo "  - Removed leftsubnet/rightsubnet (now uses policy-based routing)"
echo "  - Changed leftauth/rightauth to auth=psk"
echo "  - Changed leftid to %any"
echo "  - Removed reqid parameter"
echo "  - Added replay_window=128"
echo "  - Kept mark=1 and mark=2"

