#!/bin/bash
#
# Make Policy Routing Rules Persistent Across Reboots
#

echo "🔧 Making policy routing rules persistent..."

# Check if VPN config exists
if [ ! -f /etc/vpn/config.json ]; then
    echo "❌ VPN configuration not found at /etc/vpn/config.json"
    echo "Please run VPN Manager setup first"
    exit 1
fi

# Extract inside IP subnets from config
echo "📋 Reading VPN configuration..."
ONPREM_IPS=$(python3 -c "
import json
with open('/etc/vpn/config.json') as f:
    config = json.load(f)
    for ip in config.get('onprem_inside_ips', []):
        parts = ip.split('.')
        last_octet = int(parts[3])
        subnet_base = (last_octet // 4) * 4
        print(f'{parts[0]}.{parts[1]}.{parts[2]}.{subnet_base}/30')
")

if [ -z "$ONPREM_IPS" ]; then
    echo "❌ No inside IPs found in configuration"
    exit 1
fi

echo "Found inside IP subnets:"
echo "$ONPREM_IPS"

# Create systemd service with dynamic rules
cat > /etc/systemd/system/vpn-policy-routing.service << 'EOF'
[Unit]
Description=VPN Policy Routing Rules
After=network.target
Before=frr.service strongswan.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash /etc/vpn/apply_policy_routing.sh

[Install]
WantedBy=multi-user.target
EOF

# Create the script that applies rules
cat > /etc/vpn/apply_policy_routing.sh << EOF
#!/bin/bash
# Apply VPN policy routing rules
# Auto-generated by VPN Manager

# Remove any existing rules
$(echo "$ONPREM_IPS" | while read subnet; do
    echo "ip rule del to $subnet table main priority 100 2>/dev/null || true"
done)

# Add policy routing rules
$(echo "$ONPREM_IPS" | while read subnet; do
    echo "ip rule add to $subnet table main priority 100"
done)

# Flush route cache
ip route flush cache

echo "VPN policy routing rules applied"
EOF

chmod +x /etc/vpn/apply_policy_routing.sh

# Enable the service
systemctl daemon-reload
systemctl enable vpn-policy-routing.service

echo "✅ Policy routing rules will persist across reboots"
echo ""
echo "Files created:"
echo "  - /etc/systemd/system/vpn-policy-routing.service"
echo "  - /etc/vpn/apply_policy_routing.sh"
echo ""
echo "Service enabled: vpn-policy-routing.service"
echo ""
echo "To check service status: systemctl status vpn-policy-routing"
